application: egosize
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- appstats: on
- remote_api: on

inbound_services:
- channel_presence

libraries:
- name: lxml
  version: latest
- name: markupsafe
  version: latest
- name: ssl
  version: latest

handlers:
- url: /bootstrap
  static_dir: static/bootstrap
- url: /styles
  static_dir: static/styles
- url: /scripts
  static_dir: static/scripts
- url: /images
  static_dir: static/images

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
- url: /humans\.txt
  static_files: static/humans.txt
  upload: static/humans\.txt

- url: /(.+\.ico)
  static_files: static/\1
  upload: static/(.+\.ico)

- url: /.*
  script: index.app

